### ISSUE TITLE
How to output mIoU and mAP?

### ISSUE THREAD

**Issue by nguyentritai2906** [DeepSceneSeg/EfficientPS#26]
Hello authors. Thank you for the great work.
In your paper you reported that the model achieves mIoU of 84.2% and AP of 39.1% but I can't figure out how to output mIoU and mAP. I tried passing  `--eval panoptic cityscapes` and other metrics when calling `test.py` but not thing work so far. Below is the traceback.
Edit: Actually I have tried calculate mIoU from the model output and it is quite close to your result. But I can not find a way to get the model confidence score of the bounding box for AP calculation. How should I do it?
 
```python
Traceback (most recent call last):
  File "/content/EfficientPS/tools/test.py", line 171, in <module>
    main()
  File "/content/EfficientPS/tools/test.py", line 167, in main
    dataset.evaluate(outputs, args.eval, **kwargs)
  File "/content/EfficientPS/mmdet/datasets/cityscapes.py", line 244, in evaluate
    classwise, proposal_nums, iou_thrs))
  File "/content/EfficientPS/mmdet/datasets/coco.py", line 327, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/content/EfficientPS/mmdet/datasets/coco.py", line 281, in format_results
    format(len(results), len(self)))
AssertionError: The length of results is not equal to the dataset len: 0 != 500
```

**Comment by mohan1914** [comment]
Currently, the code-base doesn't support any evaluation other than panoptic since we report mIoU and AP in the paper for the sake of completeness. In the next update we will consider to add the additional metrics. 
Meanwhile you can save the semantic predictions for mIoU and Instance predictions for AP and directly use Cityscapes evaluation codes.
Additionally, 84.2% and 39.1% are numbers reported for the test set with mapillary pre-training and multi-scale. 
We only provide the cityscapes trained model and single scale testing for now.
